
CREATE TABLE USUARIO (
    id INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    SENHA_HASH VARCHAR(255) NOT NULL
);

CREATE TABLE PROVEDORES_DE_SERVICO (
    id INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    DESCRICAO_PROFISSIONAL TEXT,
    SENHA_HASH VARCHAR(255) NOT NULL
);

CREATE TABLE ATENDENTE (
    id INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    SENHA_HASH VARCHAR(255) NOT NULL
);

CREATE TABLE ENDERECOS (
    id INT PRIMARY KEY AUTO_INCREMENT,
    CEP VARCHAR(9) NOT NULL,
    RUA VARCHAR(255) NOT NULL,
    NUMERO_CASA VARCHAR(10),
    BAIRRO VARCHAR(100),
    ID_USUARIO INT,
    ID_PROVEDOR INT,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(id),
    FOREIGN KEY (ID_PROVEDOR) REFERENCES PROVEDORES_DE_SERVICO(id)
);

CREATE TABLE TELEFONES (
    id INT PRIMARY KEY AUTO_INCREMENT,
    TELEFONE VARCHAR(15) NOT NULL,
    TIPO VARCHAR(20),
    ID_USUARIO INT,
    ID_PROVEDOR INT,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(id),
    FOREIGN KEY (ID_PROVEDOR) REFERENCES PROVEDORES_DE_SERVICO(id)
);

CREATE TABLE CATEGORIAS (
    id INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE PROVEDOR_CATEGORIA (
    ID_PROVEDOR INT NOT NULL,
    ID_CATEGORIA INT NOT NULL,
    PRIMARY KEY (ID_PROVEDOR, ID_CATEGORIA),
    FOREIGN KEY (ID_PROVEDOR) REFERENCES PROVEDORES_DE_SERVICO(id),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(id)
);

CREATE TABLE SERVICOS (
    id INT PRIMARY KEY AUTO_INCREMENT,
    NOME_SERVICO VARCHAR(255) NOT NULL,
    DESCRICAO TEXT,
    PRECO DECIMAL(10, 2),
    ID_PROVEDOR INT,
    FOREIGN KEY (ID_PROVEDOR) REFERENCES PROVEDORES_DE_SERVICO(id)
);

CREATE TABLE DEMANDAS (
    id INT PRIMARY KEY AUTO_INCREMENT,
    STATUS VARCHAR(50),
    DATA_INICIO DATE,
    DATA_CONCLUSAO DATE,
    ID_SERVICO INT,
    ID_USUARIO INT,
    ID_PROVEDOR INT,
    FOREIGN KEY (ID_SERVICO) REFERENCES SERVICOS(id),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(id),
    FOREIGN KEY (ID_PROVEDOR) REFERENCES PROVEDORES_DE_SERVICO(id)
);

CREATE TABLE AVALIACOES (
    id INT PRIMARY KEY AUTO_INCREMENT,
    NOTA INT NOT NULL,
    COMENTARIO TEXT,
    DATA_AVALIACAO DATETIME NOT NULL,
    ID_DEMANDA INT NOT NULL UNIQUE,
    FOREIGN KEY (ID_DEMANDA) REFERENCES DEMANDAS(id)
);

CREATE TABLE CHAMADOS (
    id INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO TEXT NOT NULL,
    DATA_CHAMADO DATE,
    ID_ATENDENTE INT,
    ID_DEMANDA INT,
    FOREIGN KEY (ID_ATENDENTE) REFERENCES ATENDENTE(id),
    FOREIGN KEY (ID_DEMANDA) REFERENCES DEMANDAS(id)
);
